version: '3'

services:
  master:
    build: ..
    command: master
    tty: true
    ports:
      - "60000"
    volumes:
      - "./test/:/jmeter/apache-jmeter-5.0/bin/plan/"
    networks:
      - jmeter-network
  server:
    build: ..
    command: server
    tty: true
    ports:
      - "50000"
      - "1099"
    volumes:
      - "./test/:/jmeter/apache-jmeter-5.0/bin/plan/"
    networks:
      - jmeter-network
    depends_on:
      - master

networks:
  jmeter-network:
